### PR TITLE
Prepare release 0.3.0

### PR DESCRIPTION
**Pull request by arkgil**

### CODE REVIEW

**Comment by wojtekmach** [comment]
Don't forget to update docs version :) https://github.com/beam-telemetry/telemetry/blob/prepare-release-0.3.0/doc/overview.edoc#L2

**Comment by arkgil** [comment]
@wojtekmach Oops, thanks!

**Comment by arkgil** [comment]
I need to update the version in docs anyway (unless there is some rebar.config+edoc magic I could use to make it fill automatically 😄). But I agree about people depending on git version, I haven’t thought about it.

**Comment by tsloughter** [comment]
Yea, even if you have to do a commit to change version else where (I'll have to look into getting around that with edoc, not sure if rebar3 has to be made to handle that) it is still nice for when being used as a dep pointing to the git repo, so no reason to not leave it as `git` as far as I know.

**Pull request merged**
